// Lista de juegos COMPLETA con todos los campos ampliados
const juegos = [
  {
    id: 1,
    nombre: "God of War Ragnarök",
    precio: 59.99,
    // IMÁGENES MÚLTIPLES - ARRAY NUEVO
    imagenes: [
      "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
      "https://example.com/gow-2.jpg",
      "https://example.com/gow-3.jpg",
      "https://example.com/gow-4.jpg"
    ],
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
    categoria: "Acción-Aventura",
    plataforma: "PS5",
    descripcion: "Una épica aventura nórdica con Kratos y Atreus",
    descripcionCompleta: "En God of War Ragnarök, acompaña a Kratos y Atreus en una épica travesía por los Nueve Reinos mientras el fin del mundo se aproxima. La relación entre padre e hijo se verá puesta a prueba frente a poderosos dioses, criaturas legendarias y decisiones que marcarán su destino. Con un apartado visual impresionante, combates más feroces y escenarios llenos de misterios, esta secuela eleva la saga a nuevas alturas de emoción y profundidad. A medida que el Ragnarök se acerca, Kratos deberá elegir entre romper el ciclo de la violencia o aceptar su legado de guerra, mientras Atreus busca comprender quién es y cuál es su verdadero propósito. Cada batalla, cada decisión y cada paso los acercan al desenlace de una historia donde el honor, el sacrificio y la familia lo significan todo.",
    plataformas: ["PS5", "PS4"],
    calificacion: 4.8,
    reseñas: 1250,
    disponibilidad: "En stock",
    stock: 15,
    caracteristicas: ["Modo Historia", "Gráficos 4K", "DualSense", "Mundo Abierto"],
    desarrollador: "Santa Monica Studio",
    lanzamiento: "2022",
    genero: "Acción-Aventura"
  },
  {
    id: 2,
    nombre: "The Legend of Zelda: TOTK",
    precio: 69.99,
    imagen: "https://i.redd.it/4rkflsjclf0b1.png",
    categoria: "Aventura",
    plataforma: "Nintendo Switch",
    descripcion: "Explora los cielos y las profundidades de Hyrule",
    descripcionCompleta: "Viaja por los cielos y descubre los secretos del reino de Hyrule en esta secuela del aclamado Breath of the Wild. Construye, crea y resuelve puzzles de formas nunca antes vistas.",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.9,
    reseñas: 890,
    disponibilidad: "En stock",
    stock: 8,
    caracteristicas: ["Mundo Abierto", "Física Realista", "120+ Horas", "Construcción"],
    desarrollador: "Nintendo",
    lanzamiento: "2023",
    genero: "Aventura"
  },
  {
    id: 3,
    nombre: "Cyberpunk 2077",
    precio: 49.99,
    imagen: "https://press.cdprojektred.com/_next/image?url=https%3A%2F%2Fpress.cdn.cdpr.app%2Fnews%2F6fdf182c4be4a018da07e1703f3a21aefb6d5833525d8ec1.png&w=1920&q=75",
    categoria: "RPG",
    plataforma: "PC",
    descripcion: "Un RPG de mundo abierto en Night City",
    descripcionCompleta: "Sumérgete en el mundo distópico de Night City, una metrópolis obsesionada con el poder, la moda y las modificaciones corporales. Tu personaje, V, busca un implante único que es la clave para la inmortalidad.",
    plataformas: ["PC", "PS5", "Xbox Series X"],
    calificacion: 4.3,
    reseñas: 2100,
    disponibilidad: "En stock",
    stock: 22,
    caracteristicas: ["Ray Tracing", "Personalización", "Historia No Lineal", "Mundo Abierto"],
    desarrollador: "CD Projekt Red",
    lanzamiento: "2020",
    genero: "RPG"
  },
  {
    id: 4,
    nombre: "FIFA 24",
    precio: 69.99,
    imagen: "https://cdn2.unrealengine.com/hero-image-1920x1086-7c2bd7ea7c42.jpg",
    categoria: "Deportes",
    plataforma: "PS5",
    descripcion: "El mejor juego de fútbol del mundo",
    descripcionCompleta: "La experiencia de fútbol más auténtica con HyperMotion2, Cross-Play y todas las ligas oficiales. Vive la emoción del deporte rey con gráficos de última generación.",
    plataformas: ["PS5", "Xbox Series X", "PC", "Nintendo Switch"],
    calificacion: 4.2,
    reseñas: 1800,
    disponibilidad: "En stock",
    stock: 30,
    caracteristicas: ["Ultimate Team", "Cross-Play", "Licencias Oficiales", "Modo Carrera"],
    desarrollador: "EA Sports",
    lanzamiento: "2023",
    genero: "Deportes"
  },
  {
    id: 5,
    nombre: "Halo Infinite",
    precio: 54.99,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr2KPhjfZ9PQRWN8YyBRRb6x6BK5FisSwDrA&s",
    categoria: "Shooter",
    plataforma: "Xbox Series X",
    descripcion: "La legendaria franquicia de shooter regresa",
    descripcionCompleta: "El Jefe Maestro regresa en la aventura más grande de Halo hasta la fecha. Explora el anillo Halo en mundo abierto y disfruta del multijugador gratuito.",
    plataformas: ["Xbox Series X", "Xbox One", "PC"],
    calificacion: 4.4,
    reseñas: 950,
    disponibilidad: "En stock",
    stock: 12,
    caracteristicas: ["Multijugador Gratuito", "Mundo Abierto", "Campo de Batalla", "Gráficos 4K"],
    desarrollador: "343 Industries",
    lanzamiento: "2021",
    genero: "Shooter"
  },
  {
    id: 6,
    nombre: "Super Mario Odyssey",
    precio: 49.99,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4-9bFb82p4QTFbgB22CXva8GCFDhZR4QZWg&s",
    categoria: "Aventura",
    plataforma: "Nintendo Switch",
    descripcion: "Únete a Mario en una aventura alrededor del mundo",
    descripcionCompleta: "Acompaña a Mario y Cappy en un viaje alrededor del globo para rescatar a la Princesa Peach de Bowser. Lanza tu sombrero para poseer personajes y objetos.",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.7,
    reseñas: 1100,
    disponibilidad: "En stock",
    stock: 18,
    caracteristicas: ["Mundo Abierto", "Mecánica de Sombrero", "Co-op", "Rejugabilidad"],
    desarrollador: "Nintendo",
    lanzamiento: "2017",
    genero: "Aventura"
  },
  {
    id: 7,
    nombre: "Elden Ring",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/phvVT0qZfcRms5qDAk0SI3CM.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    descripcion: "Un épico RPG de mundo abierto",
    descripcionCompleta: "Un RPG de mundo abierto creado por FromSoftware y George R.R. Martin. Explora las Tierras Intermedias, descubre secretos y enfréntate a jefes colosales.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.9,
    reseñas: 3200,
    disponibilidad: "En stock",
    stock: 25,
    caracteristicas: ["Mundo Abierto", "Combate Desafiante", "Cooperativo", "Personalización"],
    desarrollador: "FromSoftware",
    lanzamiento: "2022",
    genero: "RPG"
  },
  {
    id: 8,
    nombre: "Spider-Man 2",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/60eca3ac155247e21850c7d075a13d5c0b10ec7f5e15f7e6.png",
    categoria: "Acción-Aventura",
    plataforma: "PS5",
    descripcion: "Vive la aventura de Peter Parker y Miles Morales",
    descripcionCompleta: "Juega como ambos Spider-Men mientras protegen la Nueva York Marvel de nuevos y peligrosos villanos. Nuevas habilidades, trajes y una historia emocionante.",
    plataformas: ["PS5"],
    calificacion: 4.8,
    reseñas: 890,
    disponibilidad: "En stock",
    stock: 14,
    caracteristicas: ["Dos Protagonistas", "Nueva York Abierta", "Trajes Clásicos", "Historia Épica"],
    desarrollador: "Insomniac Games",
    lanzamiento: "2023",
    genero: "Acción-Aventura"
  },
  {
    id: 9,
    nombre: "Starfield",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202202/2322/4Q0sBjeaMk2Wb6pEy8RchXhX.png",
    categoria: "RPG",
    plataforma: "Xbox Series X/PC",
    descripcion: "Explora la galaxia en este masivo RPG espacial",
    descripcionCompleta: "El próximo gran RPG de los creadores de Skyrim y Fallout. Explora más de 1000 planetas, personaliza tu nave y descubre los secretos del universo.",
    plataformas: ["Xbox Series X", "PC"],
    calificacion: 4.5,
    reseñas: 1500,
    disponibilidad: "En stock",
    stock: 20,
    caracteristicas: ["1000+ Planetas", "Naves Personalizables", "Historia No Lineal", "Modo Foto"],
    desarrollador: "Bethesda Game Studios",
    lanzamiento: "2023",
    genero: "RPG"
  },
  {
    id: 10,
    nombre: "Baldur's Gate 3",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2321/8b99a2ac74f52e3d59e03eb31c3b7b6d2eea0d8d3b2a6d9f.png",
    categoria: "RPG",
    plataforma: "PC/PS5",
    descripcion: "RPG galardonado con combate por turnos",
    descripcionCompleta: "Un RPG basado en D&D con combate por turnos, narrativa profunda y decisiones que importan. Reúne a tu party y enfréntate a dioses y demonios.",
    plataformas: ["PC", "PS5", "Xbox Series X"],
    calificacion: 4.9,
    reseñas: 2800,
    disponibilidad: "En stock",
    stock: 16,
    caracteristicas: ["Combate por Turnos", "Cooperativo", "Decisiones Importantes", "Personalización"],
    desarrollador: "Larian Studios",
    lanzamiento: "2023",
    genero: "RPG"
  },
  {
    id: 11,
    nombre: "Call of Duty: Modern Warfare III",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202308/1020/1d85c3ed6a5e7389cbf7f7b6f6c6f6c6a1b2c3d4e5f6a7b8.png",
    categoria: "Shooter",
    plataforma: "Multiplataforma",
    descripcion: "La entrega más reciente de la saga de shooter",
    descripcionCompleta: "Regresa Task Force 141 en la secuela directa de Modern Warfare II. Campaña emocionante, multijugador mejorado y el regreso de todos los mapas de MW2 original.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.1,
    reseñas: 1900,
    disponibilidad: "En stock",
    stock: 28,
    caracteristicas: ["Multijugador 6v6", "Mapas Clásicos", "Zombies", "Warzone"],
    desarrollador: "Sledgehammer Games",
    lanzamiento: "2023",
    genero: "Shooter"
  },
  {
    id: 12,
    nombre: "Animal Crossing: New Horizons",
    precio: 54.99,
    imagen: "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000027669/32b85837beeefdbfbfe3b2b1d8c6bdf5b1d5c2d3e4f5a6b7c8",
    categoria: "Simulación",
    plataforma: "Nintendo Switch",
    descripcion: "Crea tu paraíso personal en una isla desierta",
    descripcionCompleta: "Personaliza tu isla, haz amigos animales y crea el paraíso de tus sueños. Pesca, caza insectos, decora tu casa y disfruta de la vida tranquila.",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.8,
    reseñas: 2400,
    disponibilidad: "En stock",
    stock: 10,
    caracteristicas: ["Personalización", "Multijugador", "Eventos Estacionales", "Modo Creativo"],
    desarrollador: "Nintendo",
    lanzamiento: "2020",
    genero: "Simulación"
  },
  {
    id: 13,
    nombre: "Resident Evil 4 Remake",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/2f5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e.png",
    categoria: "Survival Horror",
    plataforma: "Multiplataforma",
    descripcion: "Reimaginación del clásico de terror",
    descripcionCompleta: "Leon S. Kennedy regresa en esta reimaginación del clásico de 2005. Gráficos modernos, jugabilidad actualizada y nueva historia.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.7,
    reseñas: 1300,
    disponibilidad: "En stock",
    stock: 17,
    caracteristicas: ["Gráficos Next-Gen", "Jugabilidad Actualizada", "Modo Mercenarios", "VR"],
    desarrollador: "Capcom",
    lanzamiento: "2023",
    genero: "Survival Horror"
  },
  {
    id: 14,
    nombre: "Forza Horizon 5",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202108/0420/5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e.png",
    categoria: "Carreras",
    plataforma: "Xbox Series X/PC",
    descripcion: "Explora los vibrantes paisajes de México",
    descripcionCompleta: "El festival de coches abierto más grande llega a México. Conduce cientos de coches a través de desiertos, junglas y ciudades.",
    plataformas: ["Xbox Series X", "PC"],
    calificacion: 4.6,
    reseñas: 1600,
    disponibilidad: "En stock",
    stock: 22,
    caracteristicas: ["Mundo Abierto", "500+ Coches", "Clima Dinámico", "Multijugador"],
    desarrollador: "Playground Games",
    lanzamiento: "2021",
    genero: "Carreras"
  },
  {
    id: 15,
    nombre: "Minecraft Legends",
    precio: 39.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d.png",
    categoria: "Estrategia",
    plataforma: "Multiplataforma",
    descripcion: "Acción y estrategia en el universo de Minecraft",
    descripcionCompleta: "Un nuevo tipo de aventura en el universo de Minecraft. Lidera a tus aliados en batallas estratégicas contra los piglins.",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.0,
    reseñas: 750,
    disponibilidad: "En stock",
    stock: 35,
    caracteristicas: ["Estrategia en Tiempo Real", "Cooperativo", "Mundo Familiar", "Nueva Jugabilidad"],
    desarrollador: "Mojang Studios",
    lanzamiento: "2023",
    genero: "Estrategia"
  },
  {
    id: 16,
    nombre: "Street Fighter 6",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202209/2323/23232323232323232323232323232323232323232323.png",
    categoria: "Lucha",
    plataforma: "Multiplataforma",
    descripcion: "La nueva entrega de la saga de lucha",
    descripcionCompleta: "El regreso de la legendaria saga de lucha con nuevos personajes, modos de juego innovadores y gráficos de última generación.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.5,
    reseñas: 1100,
    disponibilidad: "En stock",
    stock: 19,
    caracteristicas: ["Modo Mundo", "Combates Online", "Personajes Clásicos", "Gráficos RE"],
    desarrollador: "Capcom",
    lanzamiento: "2023",
    genero: "Lucha"
  },
  {
    id: 17,
    nombre: "The Witcher 3: Wild Hunt",
    precio: 39.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    descripcion: "Embárcate en una épica aventura como Geralt",
    descripcionCompleta: "Geralt de Rivia, cazador de monstruos, busca a su hija adoptiva en un mundo devastado por la guerra. Decisiónes que cambian la historia.",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.9,
    reseñas: 4500,
    disponibilidad: "En stock",
    stock: 40,
    caracteristicas: ["Mundo Abierto", "Decisiones Importantes", "100+ Horas", "DLC Incluido"],
    desarrollador: "CD Projekt Red",
    lanzamiento: "2015",
    genero: "RPG"
  },
  {
    id: 18,
    nombre: "Dead Space Remake",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a.png",
    categoria: "Survival Horror",
    plataforma: "PS5/Xbox Series X/PC",
    descripcion: "Terror espacial reimaginado",
    descripcionCompleta: "El clásico de terror espacial regresa con gráficos de última generación, audio 3D y jugabilidad mejorada. Enfréntate a los necromorfos en la nave Ishimura.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.6,
    reseñas: 950,
    disponibilidad: "En stock",
    stock: 13,
    caracteristicas: ["Gráficos Next-Gen", "Audio 3D", "Terror Psicológico", "Jugabilidad Mejorada"],
    desarrollador: "Motive Studio",
    lanzamiento: "2023",
    genero: "Survival Horror"
  },
  {
    id: 19,
    nombre: "Sekiro: Shadows Die Twice",
    precio: 49.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c.png",
    categoria: "Acción",
    plataforma: "Multiplataforma",
    descripcion: "Desafia la muerte en el Japón feudal",
    descripcionCompleta: "Un shinobi desfigurado busca venganza en el Japón feudal del período Sengoku. Combate de espadas intenso y mundo vertical.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.8,
    reseñas: 1800,
    disponibilidad: "En stock",
    stock: 11,
    caracteristicas: ["Combate de Espadas", "Mundo Vertical", "Postura de Combate", "Gráficos Estilizados"],
    desarrollador: "FromSoftware",
    lanzamiento: "2019",
    genero: "Acción"
  },
  {
    id: 20,
    nombre: "Persona 5 Royal",
    precio: 54.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    descripcion: "Vive la vida de estudiante y lucha contra la corrupción",
    descripcionCompleta: "Un grupo de estudiantes forma los Phantom Thieves para cambiar los corazones de adultos corruptos. Combina vida escolar y aventuras sobrenaturales.",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.9,
    reseñas: 2200,
    disponibilidad: "En stock",
    stock: 26,
    caracteristicas: ["JRPG", "Simulación Social", "Combate por Turnos", "100+ Horas"],
    desarrollador: "Atlus",
    lanzamiento: "2020",
    genero: "RPG"
  },
  {
    id: 21,
    nombre: "Gran Turismo 7",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b.png",
    categoria: "Carreras",
    plataforma: "PS5",
    descripcion: "La experiencia de conducción definitiva",
    descripcionCompleta: "El simulador de conducción más realista con cientos de coches, circuitos reales y física avanzada. Modo campaña y multijugador competitivo.",
    plataformas: ["PS5"],
    calificacion: 4.4,
    reseñas: 1200,
    disponibilidad: "En stock",
    stock: 16,
    caracteristicas: ["400+ Coches", "Circuitos Reales", "Física Realista", "VR2 Compatible"],
    desarrollador: "Polyphony Digital",
    lanzamiento: "2022",
    genero: "Carreras"
  },
  {
    id: 22,
    nombre: "Hades",
    precio: 24.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c.png",
    categoria: "Roguelike",
    plataforma: "Multiplataforma",
    descripcion: "Roguelike de acción en el Inframundo",
    descripcionCompleta: "Desafía al dios de los muertos en este roguelike de acción. Escapa del Inframundo griego mientras descubres una historia profunda.",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.8,
    reseñas: 1900,
    disponibilidad: "En stock",
    stock: 45,
    caracteristicas: ["Roguelike", "Narrativa Profunda", "Combate Rápido", "Arte Estilizado"],
    desarrollador: "Supergiant Games",
    lanzamiento: "2020",
    genero: "Roguelike"
  },
  {
    id: 23,
    nombre: "Final Fantasy XVI",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d.png",
    categoria: "RPG",
    plataforma: "PS5",
    descripcion: "Una nueva y oscura fantasía épica",
    descripcionCompleta: "Una historia oscura y madura en el universo de Final Fantasy. Combate en tiempo real, invocaciones épicas y mundo de alta fantasía.",
    plataformas: ["PS5"],
    calificacion: 4.7,
    reseñas: 850,
    disponibilidad: "En stock",
    stock: 14,
    caracteristicas: ["Combate en Tiempo Real", "Invocaciones Épicas", "Historia Madura", "Mundo Abierto"],
    desarrollador: "Square Enix",
    lanzamiento: "2023",
    genero: "RPG"
  },
  {
    id: 24,
    nombre: "Metroid Dread",
    precio: 59.99,
    imagen: "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000035867/9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e",
    categoria: "Metroidvania",
    plataforma: "Nintendo Switch",
    descripcion: "Samus Aran regresa en una aventura de acción",
    descripcionCompleta: "Samus enfrenta su misión más peligrosa contra los EMMI, robots de caza implacables. Exploración 2D y acción intensa.",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.6,
    reseñas: 780,
    disponibilidad: "En stock",
    stock: 9,
    caracteristicas: ["Metroidvania", "Exploración 2D", "EMMI Perseguidores", "Gráficos 3D"],
    desarrollador: "MercurySteam",
    lanzamiento: "2021",
    genero: "Metroidvania"
  },
  {
    id: 25,
    nombre: "Stray",
    precio: 29.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e.png",
    categoria: "Aventura",
    plataforma: "PS5/PC",
    descripcion: "Juega como un gato en una ciudad cyberpunk",
    descripcionCompleta: "Un gato callejero perdido en una ciudad de robots debe resolver un antiguo misterio para escapar. Perspectiva única y mundo detallado.",
    plataformas: ["PS5", "PC"],
    calificacion: 4.5,
    reseñas: 1600,
    disponibilidad: "En stock",
    stock: 32,
    caracteristicas: ["Perspectiva Felina", "Mundo Cyberpunk", "Puzzles", "Narrativa Emocional"],
    desarrollador: "BlueTwelve Studio",
    lanzamiento: "2022",
    genero: "Aventura"
  },
  {
    id: 26,
    nombre: "Tekken 8",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a.png",
    categoria: "Lucha",
    plataforma: "Multiplataforma",
    descripcion: "La nueva entrega de la saga de lucha",
    descripcionCompleta: "El torneo del rey del puño de hierro continúa con gráficos revolucionarios, nuevo sistema de combate y personajes clásicos.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.4,
    reseñas: 920,
    disponibilidad: "En stock",
    stock: 21,
    caracteristicas: ["Combate Heat", "Gráficos Unreal 5", "Story Mode", "Online Ranked"],
    desarrollador: "Bandai Namco",
    lanzamiento: "2024",
    genero: "Lucha"
  },
  {
    id: 27,
    nombre: "Hogwarts Legacy",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    descripcion: "Vive tu aventura en el mundo mágico",
    descripcionCompleta: "Un RPG de mundo abierto en el universo de Harry Potter del siglo XIX. Asiste a clases de magia, domina hechizos y explora Hogwarts.",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.6,
    reseñas: 2700,
    disponibilidad: "En stock",
    stock: 38,
    caracteristicas: ["Mundo Abierto", "Hechizos Personalizables", "Clases de Magia", "Animales Mágicos"],
    desarrollador: "Avalanche Software",
    lanzamiento: "2023",
    genero: "RPG"
  },
  {
    id: 28,
    nombre: "Returnal",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c.png",
    categoria: "Roguelike",
    plataforma: "PS5/PC",
    descripcion: "Shooter roguelike en un planeta alienígena",
    descripcionCompleta: "Una astronauta atrapada en un ciclo temporal en un planeta alienígena. Cada muerte la reinicia, pero el mundo cambia constantemente.",
    plataformas: ["PS5", "PC"],
    calificacion: 4.3,
    reseñas: 1100,
    disponibilidad: "En stock",
    stock: 12,
    caracteristicas: ["Roguelike", "Shooter 3D", "Mundo Cambiante", "DualSense"],
    desarrollador: "Housemarque",
    lanzamiento: "2021",
    genero: "Roguelike"
  },
  {
    id: 29,
    nombre: "Kirby and the Forgotten Land",
    precio: 54.99,
    imagen: "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000035867/3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d3d",
    categoria: "Plataformas",
    plataforma: "Nintendo Switch",
    descripcion: "La primera aventura 3D de Kirby",
    descripcionCompleta: "Kirby explora un mundo misterioso en 3D. Absorbe objetos y adquiere nuevas habilidades para rescatar a los Waddle Dees.",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.7,
    reseñas: 950,
    disponibilidad: "En stock",
    stock: 24,
    caracteristicas: ["Primer Kirby 3D", "Habilidades de Absorción", "Co-op", "Mundo Colorido"],
    desarrollador: "HAL Laboratory",
    lanzamiento: "2022",
    genero: "Plataformas"
  },
  {
    id: 30,
    nombre: "Diablo IV",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e.png",
    categoria: "ARPG",
    plataforma: "Multiplataforma",
    descripcion: "Regresa a Santuario en este oscuro RPG",
    descripcionCompleta: "El regreso de la saga de ARPG con mundo abierto, clases nuevas y la oscura historia de Santuario. Multijugador y endgame extenso.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.5,
    reseñas: 2300,
    disponibilidad: "En stock",
    stock: 29,
    caracteristicas: ["Mundo Abierto", "5 Clases", "Multijugador", "Endgame Extenso"],
    desarrollador: "Blizzard Entertainment",
    lanzamiento: "2023",
    genero: "ARPG"
  },
  {
    id: 31,
    nombre: "Grand Theft Auto V",
    precio: 29.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202202/2323/5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    descripcion: "Vive las historias de Michael, Franklin y Trevor",
    descripcionCompleta: "Tres criminales con diferentes habilidades se unen para realizar atracos épicos en la ciudad de Los Santos. Mundo abierto y GTA Online.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.8,
    reseñas: 5800,
    disponibilidad: "En stock",
    stock: 50,
    caracteristicas: ["3 Protagonistas", "Mundo Abierto", "GTA Online", "Modo Historia"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2013",
    genero: "Acción-Aventura"
  },
  {
    id: 32,
    nombre: "Grand Theft Auto: San Andreas",
    precio: 14.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    descripcion: "Sigue la historia de Carl Johnson en los 90",
    descripcionCompleta: "Carl 'CJ' Johnson regresa a Los Santos en los años 90 para enfrentar corrupción, pandillas y construir un imperio criminal.",
    plataformas: ["PS5", "Xbox Series X", "PC", "Mobile"],
    calificacion: 4.7,
    reseñas: 3200,
    disponibilidad: "En stock",
    stock: 35,
    caracteristicas: ["Años 90", "Personalización", "Territorios", "Misiones Diversas"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2004",
    genero: "Acción-Aventura"
  },
  {
    id: 33,
    nombre: "Grand Theft Auto IV",
    precio: 19.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    descripcion: "La historia de Niko Bellic en Liberty City",
    descripcionCompleta: "Niko Bellic, un inmigrante de Europa del Este, busca el sueño americano en Liberty City mientras enfrenta su pasado.",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.6,
    reseñas: 2800,
    disponibilidad: "En stock",
    stock: 28,
    caracteristicas: ["Historia Madura", "Física Realista", "Liberty City", "Decisiones Morales"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2008",
    genero: "Acción-Aventura"
  }
];

// Funciones del servicio (se mantienen igual)
export const obtenerJuegos = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(juegos);
    }, 1000);
  });
};

export const obtenerJuegoPorId = (id) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const juego = juegos.find(j => j.id === parseInt(id));
      if (juego) {
        resolve(juego);
      } else {
        reject(new Error('Juego no encontrado'));
      }
    }, 500);
  });
};

export const obtenerJuegosPorCategoria = (categoria) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const juegosFiltrados = juegos.filter(j => j.categoria === categoria);
      resolve(juegosFiltrados);
    }, 500);
  });
};

export const obtenerJuegosPorPlataforma = (plataforma) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const juegosFiltrados = juegos.filter(j => j.plataformas.includes(plataforma));
      resolve(juegosFiltrados);
    }, 500);
  });
};