// En src/servicios/juegosService.js - REEMPLAZAR todo el contenido con:

// Lista de juegos COMPLETA con todos los campos ampliados
const juegos = [
  {
    id: 1,
    nombre: "God of War Ragnarök",
    precio: 59.99,
    imagenes: [
      "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
      "https://example.com/gow-2.jpg",
      "https://example.com/gow-3.jpg",
      "https://example.com/gow-4.jpg"
    ],
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png",
    categoria: "Acción-Aventura",
    plataforma: "PS5",
    plataformas: ["PS5", "PS4"],
    calificacion: 4.8,
    reseñas: 1250,
    disponibilidad: "En stock",
    stock: 15,
    caracteristicas: ["Modo Historia", "Gráficos 4K", "DualSense", "Mundo Abierto"],
    desarrollador: "Santa Monica Studio",
    lanzamiento: "2022",
    fechaLanzamiento: "2022-11-09",
    descripcion: "Una épica aventura nórdica con Kratos y Atreus",
    descripcionCompleta: "En God of War Ragnarök, acompaña a Kratos y Atreus en una épica travesía por los Nueve Reinos mientras el fin del mundo se aproxima. La relación entre padre e hijo se verá puesta a prueba frente a poderosos dioses, criaturas legendarias y decisiones que marcarán su destino.",
    genero: "Acción-Aventura"
  },
  {
    id: 2,
    nombre: "The Legend of Zelda: TOTK",
    precio: 69.99,
    video: "sjxLF4IYnJc",
    imagenes: [
      "https://i.redd.it/4rkflsjclf0b1.png",
      "https://example.com/zelda-2.jpg"
    ],
    imagen: "https://i.redd.it/4rkflsjclf0b1.png",
    categoria: "Aventura",
    plataforma: "Nintendo Switch",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.9,
    reseñas: 890,
    disponibilidad: "En stock",
    stock: 8,
    caracteristicas: ["Mundo Abierto", "Física Realista", "120+ Horas", "Construcción"],
    desarrollador: "Nintendo",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-05-12",
    descripcion: "Explora los cielos y las profundidades de Hyrule",
    descripcionCompleta: "Viaja por los cielos y descubre los secretos del reino de Hyrule en esta secuela del aclamado Breath of the Wild. Construye, crea y resuelve puzzles de formas nunca antes vistas.",
    genero: "Aventura"
  },
  {
    id: 3,
    nombre: "Cyberpunk 2077",
    precio: 49.99,
    imagen: "https://press.cdprojektred.com/_next/image?url=https%3A%2F%2Fpress.cdn.cdpr.app%2Fnews%2F6fdf182c4be4a018da07e1703f3a21aefb6d5833525d8ec1.png&w=1920&q=75",
    categoria: "RPG",
    plataforma: "PC",
    plataformas: ["PC", "PS5", "Xbox Series X"],
    calificacion: 4.3,
    reseñas: 2100,
    disponibilidad: "En stock",
    stock: 22,
    caracteristicas: ["Ray Tracing", "Personalización", "Historia No Lineal", "Mundo Abierto"],
    desarrollador: "CD Projekt Red",
    lanzamiento: "2020",
    fechaLanzamiento: "2020-12-10",
    descripcion: "Un RPG de mundo abierto en Night City",
    descripcionCompleta: "Sumérgete en el mundo distópico de Night City, una metrópolis obsesionada con el poder, la moda y las modificaciones corporales. Tu personaje, V, busca un implante único que es la clave para la inmortalidad.",
    genero: "RPG"
  },
  {
    id: 4,
    nombre: "FIFA 24",
    precio: 69.99,
    imagen: "https://cdn2.unrealengine.com/hero-image-1920x1086-7c2bd7ea7c42.jpg",
    categoria: "Deportes",
    plataforma: "PS5",
    plataformas: ["PS5", "Xbox Series X", "PC", "Nintendo Switch"],
    calificacion: 4.2,
    reseñas: 1800,
    disponibilidad: "En stock",
    stock: 30,
    caracteristicas: ["Ultimate Team", "Cross-Play", "Licencias Oficiales", "Modo Carrera"],
    desarrollador: "EA Sports",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-09-29",
    descripcion: "El mejor juego de fútbol del mundo",
    descripcionCompleta: "La experiencia de fútbol más auténtica con HyperMotion2, Cross-Play y todas las ligas oficiales. Vive la emoción del deporte rey con gráficos de última generación.",
    genero: "Deportes"
  },
  {
    id: 5,
    nombre: "Halo Infinite",
    precio: 54.99,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRr2KPhjfZ9PQRWN8YyBRRb6x6BK5FisSwDrA&s",
    categoria: "Shooter",
    plataforma: "Xbox Series X",
    plataformas: ["Xbox Series X", "Xbox One", "PC"],
    calificacion: 4.4,
    reseñas: 950,
    disponibilidad: "En stock",
    stock: 12,
    caracteristicas: ["Multijugador Gratuito", "Mundo Abierto", "Campo de Batalla", "Gráficos 4K"],
    desarrollador: "343 Industries",
    lanzamiento: "2021",
    fechaLanzamiento: "2021-12-08",
    descripcion: "La legendaria franquicia de shooter regresa",
    descripcionCompleta: "El Jefe Maestro regresa en la aventura más grande de Halo hasta la fecha. Explora el anillo Halo en mundo abierto y disfruta del multijugador gratuito.",
    genero: "Shooter"
  },
  {
    id: 6,
    nombre: "Super Mario Odyssey",
    precio: 49.99,
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4-9bFb82p4QTFbgB22CXva8GCFDhZR4QZWg&s",
    categoria: "Aventura",
    plataforma: "Nintendo Switch",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.7,
    reseñas: 1100,
    disponibilidad: "En stock",
    stock: 18,
    caracteristicas: ["Mundo Abierto", "Mecánica de Sombrero", "Co-op", "Rejugabilidad"],
    desarrollador: "Nintendo",
    lanzamiento: "2017",
    fechaLanzamiento: "2017-10-27",
    descripcion: "Únete a Mario en una aventura alrededor del mundo",
    descripcionCompleta: "Acompaña a Mario y Cappy en un viaje alrededor del globo para rescatar a la Princesa Peach de Bowser. Lanza tu sombrero para poseer personajes y objetos.",
    genero: "Aventura"
  },
  {
    id: 7,
    nombre: "Elden Ring",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/phvVT0qZfcRms5qDAk0SI3CM.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.9,
    reseñas: 3200,
    disponibilidad: "En stock",
    stock: 25,
    caracteristicas: ["Mundo Abierto", "Combate Desafiante", "Cooperativo", "Personalización"],
    desarrollador: "FromSoftware",
    lanzamiento: "2022",
    fechaLanzamiento: "2022-02-25",
    descripcion: "Un épico RPG de mundo abierto",
    descripcionCompleta: "Un RPG de mundo abierto creado por FromSoftware y George R.R. Martin. Explora las Tierras Intermedias, descubre secretos y enfréntate a jefes colosales.",
    genero: "RPG"
  },
  {
    id: 8,
    nombre: "Spider-Man 2",
    precio: 69.99,
    imagen: "https://i.blogs.es/9cb3ad/marvel-s-spider-man/1366_2000.png",
    categoria: "Acción-Aventura",
    plataforma: "PS5",
    plataformas: ["PS5"],
    calificacion: 4.8,
    reseñas: 890,
    disponibilidad: "En stock",
    stock: 14,
    caracteristicas: ["Dos Protagonistas", "Nueva York Abierta", "Trajes Clásicos", "Historia Épica"],
    desarrollador: "Insomniac Games",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-10-20",
    descripcion: "Vive la aventura de Peter Parker y Miles Morales",
    descripcionCompleta: "Juega como ambos Spider-Men mientras protegen la Nueva York Marvel de nuevos y peligrosos villanos. Nuevas habilidades, trajes y una historia emocionante.",
    genero: "Acción-Aventura"
  },
  {
    id: 9,
    nombre: "Starfield",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202202/2322/4Q0sBjeaMk2Wb6pEy8RchXhX.png",
    categoria: "RPG",
    plataforma: "Xbox Series X/PC",
    plataformas: ["Xbox Series X", "PC"],
    calificacion: 4.5,
    reseñas: 1500,
    disponibilidad: "En stock",
    stock: 20,
    caracteristicas: ["1000+ Planetas", "Naves Personalizables", "Historia No Lineal", "Modo Foto"],
    desarrollador: "Bethesda Game Studios",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-09-06",
    descripcion: "Explora la galaxia en este masivo RPG espacial",
    descripcionCompleta: "El próximo gran RPG de los creadores de Skyrim y Fallout. Explora más de 1000 planetas, personaliza tu nave y descubre los secretos del universo.",
    genero: "RPG"
  },
  {
    id: 10,
    nombre: "Baldur's Gate 3",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2321/8b99a2ac74f52e3d59e03eb31c3b7b6d2eea0d8d3b2a6d9f.png",
    categoria: "RPG",
    plataforma: "PC/PS5",
    plataformas: ["PC", "PS5", "Xbox Series X"],
    calificacion: 4.9,
    reseñas: 2800,
    disponibilidad: "En stock",
    stock: 16,
    caracteristicas: ["Combate por Turnos", "Cooperativo", "Decisiones Importantes", "Personalización"],
    desarrollador: "Larian Studios",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-08-03",
    descripcion: "RPG galardonado con combate por turnos",
    descripcionCompleta: "Un RPG basado en D&D con combate por turnos, narrativa profunda y decisiones que importan. Reúne a tu party y enfréntate a dioses y demonios.",
    genero: "RPG"
  },
  {
    id: 11,
    nombre: "Call of Duty: Modern Warfare III",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202308/1020/1d85c3ed6a5e7389cbf7f7b6f6c6f6c6a1b2c3d4e5f6a7b8.png",
    categoria: "Shooter",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.1,
    reseñas: 1900,
    disponibilidad: "En stock",
    stock: 28,
    caracteristicas: ["Multijugador 6v6", "Mapas Clásicos", "Zombies", "Warzone"],
    desarrollador: "Sledgehammer Games",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-11-10",
    descripcion: "La entrega más reciente de la saga de shooter",
    descripcionCompleta: "Regresa Task Force 141 en la secuela directa de Modern Warfare II. Campaña emocionante, multijugador mejorado y el regreso de todos los mapas de MW2 original.",
    genero: "Shooter"
  },
  {
    id: 12,
    nombre: "Animal Crossing: New Horizons",
    precio: 54.99,
    imagen: "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000027669/32b85837beeefdbfbfe3b2b1d8c6bdf5b1d5c2d3e4f5a6b7c8",
    categoria: "Simulación",
    plataforma: "Nintendo Switch",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.8,
    reseñas: 2400,
    disponibilidad: "En stock",
    stock: 10,
    caracteristicas: ["Personalización", "Multijugador", "Eventos Estacionales", "Modo Creativo"],
    desarrollador: "Nintendo",
    lanzamiento: "2020",
    fechaLanzamiento: "2020-03-20",
    descripcion: "Crea tu paraíso personal en una isla desierta",
    descripcionCompleta: "Personaliza tu isla, haz amigos animales y crea el paraíso de tus sueños. Pesca, caza insectos, decora tu casa y disfruta de la vida tranquila.",
    genero: "Simulación"
  },
  {
    id: 13,
    nombre: "Resident Evil 4 Remake",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/2f5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e.png",
    categoria: "Survival Horror",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.7,
    reseñas: 1300,
    disponibilidad: "En stock",
    stock: 17,
    caracteristicas: ["Gráficos Next-Gen", "Jugabilidad Actualizada", "Modo Mercenarios", "VR"],
    desarrollador: "Capcom",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-03-24",
    descripcion: "Reimaginación del clásico de terror",
    descripcionCompleta: "Leon S. Kennedy regresa en esta reimaginación del clásico de 2005. Gráficos modernos, jugabilidad actualizada y nueva historia.",
    genero: "Survival Horror"
  },
  {
    id: 14,
    nombre: "Forza Horizon 5",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202108/0420/5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e5e.png",
    categoria: "Carreras",
    plataforma: "Xbox Series X/PC",
    plataformas: ["Xbox Series X", "PC"],
    calificacion: 4.6,
    reseñas: 1600,
    disponibilidad: "En stock",
    stock: 22,
    caracteristicas: ["Mundo Abierto", "500+ Coches", "Clima Dinámico", "Multijugador"],
    desarrollador: "Playground Games",
    lanzamiento: "2021",
    fechaLanzamiento: "2021-11-09",
    descripcion: "Explora los vibrantes paisajes de México",
    descripcionCompleta: "El festival de coches abierto más grande llega a México. Conduce cientos de coches a través de desiertos, junglas y ciudades.",
    genero: "Carreras"
  },
  {
    id: 15,
    nombre: "Minecraft Legends",
    precio: 39.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d4d.png",
    categoria: "Estrategia",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.0,
    reseñas: 750,
    disponibilidad: "En stock",
    stock: 35,
    caracteristicas: ["Estrategia en Tiempo Real", "Cooperativo", "Mundo Familiar", "Nueva Jugabilidad"],
    desarrollador: "Mojang Studios",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-04-18",
    descripcion: "Acción y estrategia en el universo de Minecraft",
    descripcionCompleta: "Un nuevo tipo de aventura en el universo de Minecraft. Lidera a tus aliados en batallas estratégicas contra los piglins.",
    genero: "Estrategia"
  },
  {
    id: 16,
    nombre: "Street Fighter 6",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202209/2323/23232323232323232323232323232323232323232323.png",
    categoria: "Lucha",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.5,
    reseñas: 1100,
    disponibilidad: "En stock",
    stock: 19,
    caracteristicas: ["Modo Mundo", "Combates Online", "Personajes Clásicos", "Gráficos RE"],
    desarrollador: "Capcom",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-06-02",
    descripcion: "La nueva entrega de la saga de lucha",
    descripcionCompleta: "El regreso de la legendaria saga de lucha con nuevos personajes, modos de juego innovadores y gráficos de última generación.",
    genero: "Lucha"
  },
  {
    id: 17,
    nombre: "The Witcher 3: Wild Hunt",
    precio: 39.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.9,
    reseñas: 4500,
    disponibilidad: "En stock",
    stock: 40,
    caracteristicas: ["Mundo Abierto", "Decisiones Importantes", "100+ Horas", "DLC Incluido"],
    desarrollador: "CD Projekt Red",
    lanzamiento: "2015",
    fechaLanzamiento: "2015-05-19",
    descripcion: "Embárcate en una épica aventura como Geralt",
    descripcionCompleta: "Geralt de Rivia, cazador de monstruos, busca a su hija adoptiva en un mundo devastado por la guerra. Decisiones que cambian la historia.",
    genero: "RPG"
  },
  {
    id: 18,
    nombre: "Dead Space Remake",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a.png",
    categoria: "Survival Horror",
    plataforma: "PS5/Xbox Series X/PC",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.6,
    reseñas: 950,
    disponibilidad: "En stock",
    stock: 13,
    caracteristicas: ["Gráficos Next-Gen", "Audio 3D", "Terror Psicológico", "Jugabilidad Mejorada"],
    desarrollador: "Motive Studio",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-01-27",
    descripcion: "Terror espacial reimaginado",
    descripcionCompleta: "El clásico de terror espacial regresa con gráficos de última generación, audio 3D y jugabilidad mejorada. Enfréntate a los necromorfos en la nave Ishimura.",
    genero: "Survival Horror"
  },
  {
    id: 19,
    nombre: "Sekiro: Shadows Die Twice",
    precio: 49.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c.png",
    categoria: "Acción",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.8,
    reseñas: 1800,
    disponibilidad: "En stock",
    stock: 11,
    caracteristicas: ["Combate de Espadas", "Mundo Vertical", "Postura de Combate", "Gráficos Estilizados"],
    desarrollador: "FromSoftware",
    lanzamiento: "2019",
    fechaLanzamiento: "2019-03-22",
    descripcion: "Desafia la muerte en el Japón feudal",
    descripcionCompleta: "Un shinobi desfigurado busca venganza en el Japón feudal del período Sengoku. Combate de espadas intenso y mundo vertical.",
    genero: "Acción"
  },
  {
    id: 20,
    nombre: "Persona 5 Royal",
    precio: 54.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.9,
    reseñas: 2200,
    disponibilidad: "En stock",
    stock: 26,
    caracteristicas: ["JRPG", "Simulación Social", "Combate por Turnos", "100+ Horas"],
    desarrollador: "Atlus",
    lanzamiento: "2020",
    fechaLanzamiento: "2020-03-31",
    descripcion: "Vive la vida de estudiante y lucha contra la corrupción",
    descripcionCompleta: "Un grupo de estudiantes forma los Phantom Thieves para cambiar los corazones de adultos corruptos. Combina vida escolar y aventuras sobrenaturales.",
    genero: "RPG"
  },
  {
    id: 21,
    nombre: "Gran Turismo 7",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b6b.png",
    categoria: "Carreras",
    plataforma: "PS5",
    plataformas: ["PS5"],
    calificacion: 4.4,
    reseñas: 1200,
    disponibilidad: "En stock",
    stock: 16,
    caracteristicas: ["400+ Coches", "Circuitos Reales", "Física Realista", "VR2 Compatible"],
    desarrollador: "Polyphony Digital",
    lanzamiento: "2022",
    fechaLanzamiento: "2022-03-04",
    descripcion: "La experiencia de conducción definitiva",
    descripcionCompleta: "El simulador de conducción más realista con cientos de coches, circuitos reales y física avanzada. Modo campaña y multijugador competitivo.",
    genero: "Carreras"
  },
  {
    id: 22,
    nombre: "Hades",
    precio: 24.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c7c.png",
    categoria: "Roguelike",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.8,
    reseñas: 1900,
    disponibilidad: "En stock",
    stock: 45,
    caracteristicas: ["Roguelike", "Narrativa Profunda", "Combate Rápido", "Arte Estilizado"],
    desarrollador: "Supergiant Games",
    lanzamiento: "2020",
    fechaLanzamiento: "2020-09-17",
    descripcion: "Roguelike de acción en el Inframundo",
    descripcionCompleta: "Desafía al dios de los muertos en este roguelike de acción. Escapa del Inframundo griego mientras descubres una historia profunda.",
    genero: "Roguelike"
  },
  {
    id: 23,
    nombre: "Final Fantasy XVI",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d8d.png",
    categoria: "RPG",
    plataforma: "PS5",
    plataformas: ["PS5"],
    calificacion: 4.7,
    reseñas: 850,
    disponibilidad: "En stock",
    stock: 14,
    caracteristicas: ["Combate en Tiempo Real", "Invocaciones Épicas", "Historia Madura", "Mundo Abierto"],
    desarrollador: "Square Enix",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-06-22",
    descripcion: "Una nueva y oscura fantasía épica",
    descripcionCompleta: "Una historia oscura y madura en el universo de Final Fantasy. Combate en tiempo real, invocaciones épicas y mundo de alta fantasía.",
    genero: "RPG"
  },
  {
    id: 24,
    nombre: "Metroid Dread",
    precio: 59.99,
    imagen: "https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000035867/9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e",
    categoria: "Metroidvania",
    plataforma: "Nintendo Switch",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.6,
    reseñas: 780,
    disponibilidad: "En stock",
    stock: 9,
    caracteristicas: ["Metroidvania", "Exploración 2D", "EMMI Perseguidores", "Gráficos 3D"],
    desarrollador: "MercurySteam",
    lanzamiento: "2021",
    fechaLanzamiento: "2021-10-08",
    descripcion: "Samus Aran regresa en una aventura de acción",
    descripcionCompleta: "Samus enfrenta su misión más peligrosa contra los EMMI, robots de caza implacables. Exploración 2D y acción intensa.",
    genero: "Metroidvania"
  },
  {
    id: 25,
    nombre: "Stray",
    precio: 29.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e9e.png",
    categoria: "Aventura",
    plataforma: "PS5/PC",
    plataformas: ["PS5", "PC"],
    calificacion: 4.5,
    reseñas: 1600,
    disponibilidad: "En stock",
    stock: 32,
    caracteristicas: ["Perspectiva Felina", "Mundo Cyberpunk", "Puzzles", "Narrativa Emocional"],
    desarrollador: "BlueTwelve Studio",
    lanzamiento: "2022",
    fechaLanzamiento: "2022-07-19",
    descripcion: "Juega como un gato en una ciudad cyberpunk",
    descripcionCompleta: "Un gato callejero perdido en una ciudad de robots debe resolver un antiguo misterio para escapar. Perspectiva única y mundo detallado.",
    genero: "Aventura"
  },
  {
    id: 26,
    nombre: "Tekken 8",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a.png",
    categoria: "Lucha",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.4,
    reseñas: 920,
    disponibilidad: "En stock",
    stock: 21,
    caracteristicas: ["Combate Heat", "Gráficos Unreal 5", "Story Mode", "Online Ranked"],
    desarrollador: "Bandai Namco",
    lanzamiento: "2024",
    fechaLanzamiento: "2024-01-26",
    descripcion: "La nueva entrega de la saga de lucha",
    descripcionCompleta: "El torneo del rey del puño de hierro continúa con gráficos revolucionarios, nuevo sistema de combate y personajes clásicos.",
    genero: "Lucha"
  },
  {
    id: 27,
    nombre: "Hogwarts Legacy",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b.png",
    categoria: "RPG",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.6,
    reseñas: 2700,
    disponibilidad: "En stock",
    stock: 38,
    caracteristicas: ["Mundo Abierto", "Hechizos Personalizables", "Clases de Magia", "Animales Mágicos"],
    desarrollador: "Avalanche Software",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-02-10",
    descripcion: "Vive tu aventura en el mundo mágico",
    descripcionCompleta: "Un RPG de mundo abierto en el universo de Harry Potter del siglo XIX. Asiste a clases de magia, domina hechizos y explora Hogwarts.",
    genero: "RPG"
  },
  {
    id: 28,
    nombre: "Returnal",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c2c.png",
    categoria: "Roguelike",
    plataforma: "PS5/PC",
    plataformas: ["PS5", "PC"],
    calificacion: 4.3,
    reseñas: 1100,
    disponibilidad: "En stock",
    stock: 12,
    caracteristicas: ["Roguelike", "Shooter 3D", "Mundo Cambiante", "DualSense"],
    desarrollador: "Housemarque",
    lanzamiento: "2021",
    fechaLanzamiento: "2021-04-30",
    descripcion: "Shooter roguelike en un planeta alienígena",
    descripcionCompleta: "Una astronauta atrapada en un ciclo temporal en un planeta alienígena. Cada muerte la reinicia, pero el mundo cambia constantemente.",
    genero: "Roguelike"
  },
  {
    id: 29,
    nombre: "Kirby and the Forgotten Land",
    precio: 54.99,
    imagen: "	https://media.rawg.io/media/resize/1920/-/screenshots/371/371b7bf344d3f2a76f7a7b6a6b4323c8.jpg",
    categoria: "Plataformas",
    plataforma: "Nintendo Switch",
    plataformas: ["Nintendo Switch"],
    calificacion: 4.7,
    reseñas: 950,
    disponibilidad: "En stock",
    stock: 24,
    caracteristicas: ["Primer Kirby 3D", "Habilidades de Absorción", "Co-op", "Mundo Colorido"],
    desarrollador: "HAL Laboratory",
    lanzamiento: "2022",
    fechaLanzamiento: "2022-03-25",
    descripcion: "La primera aventura 3D de Kirby",
    descripcionCompleta: "Kirby explora un mundo misterioso en 3D. Absorbe objetos y adquiere nuevas habilidades para rescatar a los Waddle Dees.",
    genero: "Plataformas"
  },
  {
    id: 30,
    nombre: "Diablo IV",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e4e.png",
    categoria: "ARPG",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.5,
    reseñas: 2300,
    disponibilidad: "En stock",
    stock: 29,
    caracteristicas: ["Mundo Abierto", "5 Clases", "Multijugador", "Endgame Extenso"],
    desarrollador: "Blizzard Entertainment",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-06-06",
    descripcion: "Regresa a Santuario en este oscuro RPG",
    descripcionCompleta: "El regreso de la saga de ARPG con mundo abierto, clases nuevas y la oscura historia de Santuario. Multijugador y endgame extenso.",
    genero: "ARPG"
  },
  {
    id: 31,
    nombre: "Grand Theft Auto V",
    precio: 29.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202202/2323/5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f5f.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.8,
    reseñas: 5800,
    disponibilidad: "En stock",
    stock: 50,
    caracteristicas: ["3 Protagonistas", "Mundo Abierto", "GTA Online", "Modo Historia"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2013",
    fechaLanzamiento: "2013-09-17",
    descripcion: "Vive las historias de Michael, Franklin y Trevor",
    descripcionCompleta: "Tres criminales con diferentes habilidades se unen para realizar atracos épicos en la ciudad de Los Santos. Mundo abierto y GTA Online.",
    genero: "Acción-Aventura"
  },
  {
    id: 32,
    nombre: "Grand Theft Auto: San Andreas",
    precio: 14.99,
    video: "vvmfbN2KrqI",
    imagen: "https://i.pinimg.com/736x/a4/e6/fa/a4e6fa3e10463e110e455b59843f8231.jpg",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC", "Mobile"],
    calificacion: 4.7,
    reseñas: 3200,
    disponibilidad: "En stock",
    stock: 35,
    caracteristicas: ["Años 90", "Personalización", "Territorios", "Misiones Diversas"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2004",
    fechaLanzamiento: "2004-10-26",
    descripcion: "Sigue la historia de Carl Johnson en los 90",
    descripcionCompleta: "Carl 'CJ' Johnson regresa a Los Santos en los años 90 para enfrentar corrupción, pandillas y construir un imperio criminal.",
    genero: "Acción-Aventura"
  },
  {
    id: 33,
    nombre: "Grand Theft Auto IV",
    precio: 19.99,
    video: "hvoD7ehZPcM",
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b7b.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.6,
    reseñas: 2800,
    disponibilidad: "En stock",
    stock: 28,
    caracteristicas: ["Historia Madura", "Física Realista", "Liberty City", "Decisiones Morales"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2008",
    fechaLanzamiento: "2008-04-29",
    descripcion: "La historia de Niko Bellic en Liberty City",
    descripcionCompleta: "Niko Bellic, un inmigrante de Europa del Este, busca el sueño americano en Liberty City mientras enfrenta su pasado.",
    genero: "Acción-Aventura"
  },
  {
    id: 34,
    nombre: "Counter-Strike 2",
    precio: 0.00,
    imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/730/capsule_616x353.jpg",
    categoria: "Shooter",
    plataforma: "PC",
    plataformas: ["PC"],
    calificacion: 4.8,
    reseñas: 1850000,
    disponibilidad: "En stock",
    stock: 9999,
    caracteristicas: ["Gratuito", "Competitivo", "5v5", "Modos Comunidad"],
    desarrollador: "Valve",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-09-27",
    descripcion: "El shooter táctico competitivo más popular del mundo",
    descripcionCompleta: "Counter-Strike 2 representa la mayor evolución técnica en la historia de la saga. Construido sobre el motor Source 2, ofrece renderizado moderno, servidores de subtick y herramientas comunitarias actualizadas.",
    genero: "Shooter Táctico"
  },
  {
    id: 35,
    nombre: "Left 4 Dead 2",
    precio: 9.99,
    imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/550/capsule_616x353.jpg",
    categoria: "Shooter",
    plataforma: "PC",
    plataformas: ["PC", "Xbox Series X"],
    calificacion: 4.9,
    reseñas: 420000,
    disponibilidad: "En stock",
    stock: 5000,
    caracteristicas: ["Cooperativo", "Modo Campaña", "Zombies", "Modos Versus"],
    desarrollador: "Valve",
    lanzamiento: "2009",
    fechaLanzamiento: "2009-11-17",
    descripcion: "Cooperativo zombie con tus amigos",
    descripcionCompleta: "Este shooter de acción cooperativo te lleva por el sur de EE.UU. cinco años después de la apocalipsis zombie. Juega con hasta 3 amigos contra hordas de infectados.",
    genero: "Survival Horror"
  },
  {
    id: 36,
    nombre: "Fortnite",
    precio: 0.00,
    imagen: "https://cdn2.unrealengine.com/14br-consoles-1920x1080-wlogo-1920x1080-432974386.jpg",
    categoria: "Battle Royale",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Nintendo Switch", "Mobile"],
    calificacion: 4.5,
    reseñas: 3200000,
    disponibilidad: "En stock",
    stock: 9999,
    caracteristicas: ["Gratuito", "Construcción", "100 Jugadores", "Contenido Estacional"],
    desarrollador: "Epic Games",
    lanzamiento: "2017",
    fechaLanzamiento: "2017-07-25",
    descripcion: "Battle Royale gratuito con construcción",
    descripcionCompleta: "Lucha por ser el último en pie en Battle Royale gratis de Fortnite. Construye, dispara y sobrevive en una experiencia en constante evolución con nuevos contenidos cada temporada.",
    genero: "Battle Royale"
  },
  {
    id: 37,
    nombre: "Grand Theft Auto: Vice City",
    precio: 14.99,
    imagen: "https://w7.pngwing.com/pngs/357/365/png-transparent-gta-san-andreas-police-grand-theft-auto-san-andreas-samuel-l-jackson-grand-theft-auto-v-grand-theft-auto-iv-gta-san-andreas-background-video-game-fictional-character-arm.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Mobile"],
    calificacion: 4.7,
    reseñas: 2800,
    disponibilidad: "En stock",
    stock: 25,
    caracteristicas: ["Años 80", "Banda Sonora Icónica", "Mundo Abierto", "Historia Criminal"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2002",
    fechaLanzamiento: "2002-10-27",
    descripcion: "Crimen en los vibrantes años 80",
    descripcionCompleta: "Ambientado en los años 80, Vice City sigue la historia de Tommy Vercetti mientras construye un imperio criminal en la ciudad inspirada en Miami. Con una banda sonora icónica y ambiente único.",
    genero: "Acción-Aventura"
  },
  {
    id: 38,
    nombre: "Resident Evil 2 Remake",
    precio: 39.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a9a.png",
    categoria: "Survival Horror",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X"],
    calificacion: 4.9,
    reseñas: 89000,
    disponibilidad: "En stock",
    stock: 18,
    caracteristicas: ["Gráficos RE Engine", "Dos Campañas", "Mr. X Perseguidor", "Puzzles"],
    desarrollador: "Capcom",
    lanzamiento: "2019",
    fechaLanzamiento: "2019-01-25",
    descripcion: "Terror de supervivencia en Raccoon City",
    descripcionCompleta: "Revive el clásico de terror con gráficos de última generación. Juega como Leon Kennedy o Claire Redfield mientras intentan sobrevivir al brote zombie en Raccoon City.",
    genero: "Survival Horror"
  },
  {
    id: 39,
    nombre: "The Last of Us Part I",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202206/0720/eEczyEMDd2BLa3dtkGJVE9Id.png",
    categoria: "Acción-Aventura",
    plataforma: "PS5",
    plataformas: ["PS5", "PC"],
    calificacion: 4.9,
    reseñas: 150000,
    disponibilidad: "En stock",
    stock: 22,
    caracteristicas: ["Narrativa Profunda", "Gráficos Remasterizados", "Supervivencia", "Relación Emocional"],
    desarrollador: "Naughty Dog",
    lanzamiento: "2022",
    fechaLanzamiento: "2022-09-02",
    descripcion: "Historia emocional en un mundo post-apocalíptico",
    descripcionCompleta: "Joel, un superviviente endurecido, es contratado para sacar de contrabando a Ellie, una niña de 14 años, de una zona de cuarentena opresiva. Lo que comienza como un pequeño trabajo pronto se transforma en un viaje brutal.",
    genero: "Survival Horror"
  },
  {
    id: 40,
    nombre: "Silent Hill 2",
    precio: 49.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1b1.png",
    categoria: "Survival Horror",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X"],
    calificacion: 4.8,
    reseñas: 67000,
    disponibilidad: "En stock",
    stock: 15,
    caracteristicas: ["Terror Psicológico", "Historia Profunda", "Atmósfera Opresiva", "Multiple Endings"],
    desarrollador: "Konami",
    lanzamiento: "2024",
    fechaLanzamiento: "2024-10-08",
    descripcion: "Terror psicológico en la ciudad de Silent Hill",
    descripcionCompleta: "James Sunderland recibe una carta de su esposa fallecida, diciéndole que lo espera en su 'lugar especial' en Silent Hill. Al llegar, descubre una ciudad envuelta en niebla y habitada por criaturas grotescas.",
    genero: "Survival Horror"
  },
  {
    id: 41,
    nombre: "Outlast",
    precio: 19.99,
    imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/238320/capsule_616x353.jpg",
    categoria: "Survival Horror",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
    calificacion: 4.7,
    reseñas: 89000,
    disponibilidad: "En stock",
    stock: 30,
    caracteristicas: ["Terror de Supervivencia", "Sin Armas", "Cámara de Visión Nocturna", "Atmósfera Intensa"],
    desarrollador: "Red Barrels",
    lanzamiento: "2013",
    fechaLanzamiento: "2013-09-04",
    descripcion: "Terror de supervivencia en un manicomio",
    descripcionCompleta: "Eres Miles Upshur, un periodista independiente que investiga el Hospital Mount Massive. Armado solo con tu cámara, debes sobrevivir a los horrores dentro del manicomio abandonado.",
    genero: "Survival Horror"
  },
  {
    id: 42,
    nombre: "Apex Legends",
    precio: 0.00,
    imagen: "https://media.contentapi.ea.com/content/dam/apex-legends/images/2019/01/apex-featured-image-16x9.jpg.adapt.crop191x100.1200w.jpg",
    categoria: "Battle Royale",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
    calificacion: 4.6,
    reseñas: 1200000,
    disponibilidad: "En stock",
    stock: 9999,
    caracteristicas: ["Gratuito", "Héroes con Habilidades", "Squad de 3", "Movimiento Fluido"],
    desarrollador: "Respawn Entertainment",
    lanzamiento: "2019",
    fechaLanzamiento: "2019-02-04",
    descripcion: "Battle Royale con héroes y habilidades únicas",
    descripcionCompleta: "Apex Legends es un Battle Royale gratuito donde competidores con habilidades legendarias se enfrentan por la fama y la fortuna en los límites de la Frontera.",
    genero: "Battle Royale"
  },
  {
    id: 43,
    nombre: "Red Dead Redemption 2",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202010/0222/7e5R5wq9cQbBauY7RS9VgO7C.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X"],
    calificacion: 4.9,
    reseñas: 450000,
    disponibilidad: "En stock",
    stock: 35,
    caracteristicas: ["Mundo Abierto", "Historia Épica", "Detalles Realistas", "Online"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2018",
    fechaLanzamiento: "2018-10-26",
    descripcion: "Épica western en la América de 1899",
    descripcionCompleta: "América, 1899. Arthur Morgan y la banda de Van der Linde son forajidos en fuga. Con agentes federales y los mejores cazarrecompensas pisándoles los talones, la banda deberá robar, luchar y abrirse camino por el implacable corazón de América.",
    genero: "Acción-Aventura"
  },
  {
    id: 44,
    nombre: "Overwatch 2",
    precio: 0.00,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1c1.png",
    categoria: "Shooter",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
    calificacion: 4.3,
    reseñas: 780000,
    disponibilidad: "En stock",
    stock: 9999,
    caracteristicas: ["Gratuito", "Héroes Únicos", "5v5", "Actualizaciones Constantes"],
    desarrollador: "Blizzard Entertainment",
    lanzamiento: "2022",
    fechaLanzamiento: "2022-10-04",
    descripcion: "Shooter por equipos con héroes únicos",
    descripcionCompleta: "Reúne a tu equipo y disputa batallas en lugares de todo el mundo. Elige entre un diverso elenco de héroes, forma equipos y lucha en combates 5v5 en este shooter de acción por equipos.",
    genero: "Shooter"
  },
  {
    id: 45,
    nombre: "Alien: Isolation",
    precio: 29.99,
    imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/214490/capsule_616x353.jpg",
    categoria: "Survival Horror",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
    calificacion: 4.8,
    reseñas: 67000,
    disponibilidad: "En stock",
    stock: 20,
    caracteristicas: ["IA Adaptativa", "Sigilo", "Ambiente Retro-Futurista", "Sin Armas"],
    desarrollador: "Creative Assembly",
    lanzamiento: "2014",
    fechaLanzamiento: "2014-10-07",
    descripcion: "Supervivencia contra el xenomorfo perfecto",
    descripcionCompleta: "Descubre la verdadera terror de estar solo cuando un xenomorfo perfecto te caza en una estación espacial abandonada. Sin armas, solo tu ingenio te mantendrá con vida.",
    genero: "Survival Horror"
  },  
  {
    id: 46,
    nombre: "Grand Theft Auto VI",
    precio: 79.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202312/0112/1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 5.0,
    reseñas: 0,
    disponibilidad: "Próximamente",
    stock: 0,
    caracteristicas: ["Vice City Moderna", "Protagonistas Duales", "Mundo Abierto Masivo", "Online Integrado"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2025",
    fechaLanzamiento: "2025-09-17",
    descripcion: "La entrega más esperada de la saga GTA",
    descripcionCompleta: "Grand Theft Auto VI te lleva de regreso a Vice City en la entrega más ambiciosa de la saga. Explora un mundo abierto masivo lleno de crimen, acción y posibilidades infinitas en el paraíso criminal de Leonida con los protagonistas Lucia y Jason.",
    genero: "Acción-Aventura"
  },
  {
    id: 47,
    nombre: "Star Wars Jedi: Survivor",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d2d.png",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.7,
    reseñas: 42000,
    disponibilidad: "En stock",
    stock: 18,
    caracteristicas: ["Combate de Sables", "Fuerza Jedi", "Mundo Abierto", "Historia Canon"],
    desarrollador: "Respawn Entertainment",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-04-28",
    descripcion: "Continúa la historia de Cal Kestis",
    descripcionCompleta: "La historia de Cal Kestis continúa en esta secuela de Star Wars Jedi: Fallen Order. Cal debe mantenerse un paso por delante del Imperio en una galaxia cada vez más oscura.",
    genero: "Acción-Aventura"
  },
  {
    id: 48,
    nombre: "Mortal Kombat 1",
    precio: 69.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202306/0220/3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e3e.png",
    categoria: "Lucha",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC", "Nintendo Switch"],
    calificacion: 4.5,
    reseñas: 35000,
    disponibilidad: "En stock",
    stock: 22,
    caracteristicas: ["Kameo Fighters", "Nueva Línea Temporal", "Fatalities", "Online Competitivo"],
    desarrollador: "NetherRealm Studios",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-09-19",
    descripcion: "Reinicio de la saga de lucha mortal",
    descripcionCompleta: "Liu Kang ha recreado el universo en su imagen, dando inicio a una nueva era para Mortal Kombat. Descubre un mundo renacido con personajes clásicos reinventados.",
    genero: "Lucha"
  },
  {
    id: 49,
    nombre: "Armored Core VI: Fires of Rubicon",
    precio: 59.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/4f4f4f4f4f4f4f4f4f4f4f4f4f4f4f4f4f4f4f4f4f.png",
    categoria: "Mecha",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.6,
    reseñas: 28000,
    disponibilidad: "En stock",
    stock: 15,
    caracteristicas: ["Mechas Personalizables", "Combate Rápido", "Misiones", "FromSoftware"],
    desarrollador: "FromSoftware",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-08-25",
    descripcion: "Acción mecha de los creadores de Dark Souls",
    descripcionCompleta: "Pilota tu mecha y sumérgete en combates vertiginosos en este regreso de la saga Armored Core. Personaliza tu AC y domina el campo de batalla.",
    genero: "Mecha"
  },
  {
    id: 50,
    nombre: "Lies of P",
    precio: 49.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/5g5g5g5g5g5g5g5g5g5g5g5g5g5g5g5g5g5g5g5g5g.png",
    categoria: "Soulslike",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.4,
    reseñas: 19000,
    disponibilidad: "En stock",
    stock: 20,
    caracteristicas: ["Pinocchio Oscuro", "Combate Soulslike", "Armas Personalizables", "Historia Alternativa"],
    desarrollador: "Neowiz Games",
    lanzamiento: "2023",
    fechaLanzamiento: "2023-09-19",
    descripcion: "Un oscuro cuento de Pinocchio al estilo Souls",
    descripcionCompleta: "Inspirado en el clásico cuento de Pinocho, Lies of P es un soulslike de acción que cuenta la historia de P, un muñeco que debe encontrar a Geppetto en la ciudad desolada de Krat.",
    genero: "Soulslike"
  },
   {
    id: 50,
    nombre: "Grand Theft Auto: Vice City",
    precio: 14.99,
    imagen: "https://i.pinimg.com/736x/a4/e6/fa/a4e6fa3e10463e110e455b59843f8231.jpg",
    categoria: "Acción-Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Mobile"],
    calificacion: 4.8,
    reseñas: 3200,
    disponibilidad: "En stock",
    stock: 25,
    caracteristicas: ["Años 80", "Banda Sonora Icónica", "Mundo Abierto", "Historia Criminal"],
    desarrollador: "Rockstar Games",
    lanzamiento: "2002",
    fechaLanzamiento: "2002-10-27",
    descripcion: "Crimen en los vibrantes años 80",
    descripcionCompleta: "Ambientado en los años 80, Vice City sigue la historia de Tommy Vercetti mientras construye un imperio criminal en la ciudad inspirada en Miami. Con una banda sonora icónica y ambiente único.",
    genero: "Acción-Aventura"
  },
  {
    id: 51,
    nombre: "It Takes Two",
    precio: 39.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h6h.png",
    categoria: "Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC", "Nintendo Switch"],
    calificacion: 4.9,
    reseñas: 18000,
    disponibilidad: "En stock",
    stock: 30,
    caracteristicas: ["Cooperativo Obligatorio", "Mecánicas Variadas", "Historia Emocional", "Juego del Año"],
    desarrollador: "Hazelight Studios",
    lanzamiento: "2021",
    fechaLanzamiento: "2021-03-26",
    descripcion: "Aventura cooperativa única para dos jugadores",
    descripcionCompleta: "Una aventura cooperativa única donde dos jugadores controlan a Cody y May, una pareja en crisis transformada en muñecos. Deben trabajar juntos para superar desafíos y salvar su relación.",
    genero: "Aventura Cooperativa"
  },
  {
    id: 52,
    nombre: "Sea of Thieves",
    precio: 39.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/7i7i7i7i7i7i7i7i7i7i7i7i7i7i7i7i7i7i7i7i7i.png",
    categoria: "Aventura",
    plataforma: "Multiplataforma",
    plataformas: ["Xbox Series X", "PC", "PS5"],
    calificacion: 4.3,
    reseñas: 95000,
    disponibilidad: "En stock",
    stock: 9999,
    caracteristicas: ["Mundo Abierto", "Cooperativo", "Piratas", "Contenido Gratuito"],
    desarrollador: "Rare",
    lanzamiento: "2018",
    fechaLanzamiento: "2018-03-20",
    descripcion: "Aventura pirata en mundo compartido",
    descripcionCompleta: "Sea of Thieves ofrece la experiencia pirata definitiva, desde navegación y combate hasta exploración y saqueo. Todo en un mundo compartido y persistente.",
    genero: "Aventura Multijugador"
  },
  {
    id: 53,
    nombre: "Celeste",
    precio: 19.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/8j8j8j8j8j8j8j8j8j8j8j8j8j8j8j8j8j8j8j8j8j.png",
    categoria: "Plataformas",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.8,
    reseñas: 42000,
    disponibilidad: "En stock",
    stock: 45,
    caracteristicas: ["Plataformas Precisas", "Historia Emocional", "Banda Sonora", "Modo Assist"],
    desarrollador: "Maddy Makes Games",
    lanzamiento: "2018",
    fechaLanzamiento: "2018-01-25",
    descripcion: "Aventura de plataformas sobre superación personal",
    descripcionCompleta: "Ayuda a Madeline a escalar la Montaña Celeste en este plataformas desafiante sobre superar tus demonios internos. Controles precisos y una historia conmovedora.",
    genero: "Plataformas"
  },
  {
    id: 54,
    nombre: "Monster Hunter: World",
    precio: 29.99,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k9k.png",
    categoria: "Acción-RPG",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "PC"],
    calificacion: 4.7,
    reseñas: 120000,
    disponibilidad: "En stock",
    stock: 35,
    caracteristicas: ["Caza de Monstruos", "Cooperativo 4J", "Crafting", "Mundo Ecológico"],
    desarrollador: "Capcom",
    lanzamiento: "2018",
    fechaLanzamiento: "2018-01-26",
    descripcion: "Caza monstruos épicos en un mundo vivo",
    descripcionCompleta: "Caza monstruos gigantescos en paisajes vibrantes como cazador en un mundo vivo y que respira. Mejora tu equipo cazando monstruos cada vez más peligrosos.",
    genero: "Acción-RPG"
  },
    {
    id: 55,
    nombre: "Fall Guys: Ultimate Knockout",
    precio: 0.00,
    imagen: "https://image.api.playstation.com/vulcan/ap/rnd/202302/2323/1m1m1m1m1m1m1m1m1m1m1m1m1m1m1m1m1m1m1m1m1m.png",
    categoria: "Battle Royale",
    plataforma: "Multiplataforma",
    plataformas: ["PS5", "Xbox Series X", "Nintendo Switch", "PC"],
    calificacion: 4.4,
    reseñas: 180000,
    disponibilidad: "En stock",
    stock: 9999,
    caracteristicas: ["Gratuito", "Battle Royale Casual", "Minijuegos", "Personalización"],
    desarrollador: "Mediatonic",
    lanzamiento: "2020",
    fechaLanzamiento: "2020-08-04",
    descripcion: "Battle royale caótico y divertido",
    descripcionCompleta: "Fall Guys es un battle royale gratuito donde compites contra hasta 59 jugadores online en una carrera de obstáculos salvajes hasta la victoria.",
    genero: "Battle Royale"
  },
    {
    id: 56,
    nombre: "Stardew Valley",
    precio: 14.99,
    imagen: "https://cdn.cloudflare.steamstatic.com/steam/apps/413150/capsule_616x353.jpg",
    categoria: "Simulación",
    plataforma: "Multiplataforma",
    plataformas: ["PC", "PS5", "Xbox Series X", "Nintendo Switch", "Mobile"],
    calificacion: 4.9,
    reseñas: 380000,
    disponibilidad: "En stock",
    stock: 60,
    caracteristicas: ["Granja Personalizable", "Relaciones con NPCs", "Exploración", "Multijugador"],
    desarrollador: "ConcernedApe",
    lanzamiento: "2016",
    fechaLanzamiento: "2016-02-26",
    descripcion: "Simulación relajante de vida rural",
    descripcionCompleta: "Hereda la vieja granja de tu abuelo en Stardew Valley. Armado con herramientas de segunda mano y algunas monedas, comienzas tu nueva vida. ¿Podrás aprender a vivir de la tierra y convertir estos campos descuidados en un hogar próspero?",
    genero: "Simulación"
  }
];

// Funciones del servicio (se mantienen igual)
export const obtenerJuegos = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(juegos);
    }, 1000);
  });
};

export const obtenerJuegoPorId = (id) => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const juego = juegos.find(j => j.id === parseInt(id));
      if (juego) {
        resolve(juego);
      } else {
        reject(new Error('Juego no encontrado'));
      }
    }, 500);
  });
};

export const obtenerJuegosPorCategoria = (categoria) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const juegosFiltrados = juegos.filter(j => j.categoria === categoria);
      resolve(juegosFiltrados);
    }, 500);
  });
};

export const obtenerJuegosPorPlataforma = (plataforma) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      const juegosFiltrados = juegos.filter(j => j.plataformas.includes(plataforma));
      resolve(juegosFiltrados);
    }, 500);
  });
};